console.log("Hello world")
console.log(document.body)
console.log(document.body.childNodes)
console.log(document.body.childNodes[1])
console.log(document.body.childNodes[1].childNodes)
console.log(document.body.childNodes[1].firstChild)
console.log(document.body.childNodes[1].lastChild)